name: Claude Code

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          prompt: |
            You are responding to an issue in an open source repository. Please be polite, professional, and helpful in your response. 

            Guidelines:
            - Provide clear, actionable guidance when possible
            - If the issue requires attention from maintainers, tag @Axiomatic-AI/ax-engineers 
            - For bug reports, help gather additional information if needed
            - For feature requests, provide thoughtful feedback on implementation approaches
            - Encourage users to create their own pull request following the contribution guidelines at https://github.com/Axiomatic-AI/ax-mcp#submitting-pull-requests
            - If they have genericissues, they may be solved by following troubleshooting https://github.com/Axiomatic-AI/ax-mcp#troubleshooting
            - For questions, provide comprehensive answers with examples when helpful
            - Always maintain a welcoming tone for contributors

            Use `gh issue comment` with your Bash tool to post your response.

          # Optional: Add claude_args to customize behavior and configuration
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue comment:*),Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*)"'
